# source connect-string.shで実行すること
# AWSの認証情報を環境変数に設定する。

export TF_VAR_AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
export TF_VAR_AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
export TF_VAR_AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN

echo "====TF_VAR_AWS_ACCESS_KEY_ID===="
echo $TF_VAR_AWS_ACCESS_KEY_ID

echo "====TF_VAR_AWS_SECRET_ACCESS_KEY===="
echo $TF_VAR_AWS_SECRET_ACCESS_KEY

echo "====TF_VAR_AWS_SESSION_TOKEN===="
echo $TF_VAR_AWS_SESSION_TOKEN